### PR TITLE
Sentry Middleware

### PR DESCRIPTION
**Pull request by sam-lippert**
I have tested this against a live environment, and errors are logged successfully. Please feel free to make changes or let me know if there is anything to discuss. Thank you!

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @sam-lippert !

I've tried to run this middleware on a live environment too. It works well! Nice!

I think it's better users can add options and callback functions for, such as `sentry.setUser()`.
On the commit 8e16d4c9a0730ea114ea627ac7b70b706c665a51, that feature are implemented. We can write like below:

```ts
app.use(
  '*',
  sentry({ debug: false }, (sentry) => {
    sentry.setUser({ id: '123' })
  })
)
```

How do you think about it?

If it is OK, we have to think about Deno implementation. It's difficult to make compatibility with API for Cloudflare Workers. And, on the Deno, we can use "[sentry_deno](https://github.com/GJZwiers/sentry_deno)". This module provides the global static object `Santry`, so we can't pass the instance to the callback function.

Perhaps the Deno implementation may not be necessary. If we want to use Sentry on Deno, To use the `Sentry` object by "sentry_deno" is not so difficult.

It's just my thought.

**Comment by yusukebe** [comment]
Hi @sam-lippert !

The implementation above was still incomplete. I have some ideas. I'll write the code, please wait a little longer.

**Comment by yusukebe** [comment]
@sam-lippert 

In this commit: cbcd8fb3da5302e155cdc84c511d4719f50af414, I have remade the Deno implementation to use `toucan-js` as well. `touchan-js` is imported from `cdn.skypack.dev`.

We may use this on both Cloudflare Workers and Deno with the same syntax.

For this middleware, it's difficult to do testing. If you know a good way, please implement it. Or run it on the live environment.

**Comment by sam-lippert** [comment]
This is looking very promising. I was able to test the callback function successfully in unit tests and in the live environment, but I am getting an error when I use the Toucan-js library in deno:

```
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to send a HTTP request was started in this test, but never completed. This is often caused by not awaiting the result of a `fetch` call. The operation was started here:
    at Object.opAsync (deno:core/01_core.js:158:42)
    at opFetchSend (deno:ext/fetch/26_fetch.js:88:17)
    at mainFetch (deno:ext/fetch/26_fetch.js:287:42)
    at deno:ext/fetch/26_fetch.js:462:11
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:425:20)
    at Toucan.postEvent (https://cdn.skypack.dev/-/toucan-js@v2.6.1-CqSjx1wclyyqjmiWHWgB/dist=es2019,mode=imports/optimized/toucan-js.js:225:28)
    at Toucan.reportException (https://cdn.skypack.dev/-/toucan-js@v2.6.1-CqSjx1wclyyqjmiWHWgB/dist=es2019,mode=imports/optimized/toucan-js.js:376:17)
```

**Comment by yusukebe** [comment]
Hi @sam-lippert !

Thank you for writing the tests.

> but I am getting an error when I use the Toucan-js library in deno:

How do you get this error? In my environment, the tests are passed. Also, CI might be passed.

FYI:
The Deno code in `deno_dist` is generated automatically by using `yarn denoify` command. So, you should not rewrite the code "`deno_dist/index.ts`". And, if you update the `src/index.ts`, it's better to run `yarn denoify` to update the Deno code too.

**Comment by sam-lippert** [comment]
I was able to get the error for Deno by passing a dsn for a live Sentry environment to the Toucan constructor options in the unit test. Providing a dsn does work in the jest-based tests. It looks like when Toucan does a fetch for reporting messages and errors, it does not await the fetch unless there is an execution context that it can use for waitUntil(), causing the stack trace to be generated. The fetch is not performed if the dsn is not provided, as is the case in the unit tests.

**Comment by yusukebe** [comment]
@sam-lippert 

Okay, I understand!

First, we should not run the test for Deno with the dsn, for a live Sentry environment. The error is caused by exactly what you say. I think it's not necessary to test with dsn. The tests in current PR are enough.

But instead, we can try to run the script (not in tests) for a live Sentry environment. Like below:

```ts
import { serve } from 'https://deno.land/std/http/server.ts'
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { sentry } from '../../deno_dist/mod.ts'

const app = new Hono()

app.use(
  '*',
  sentry({
    dsn: 'https://xxxxx',
    debug: true,
  })
)

app.get('/', (c) => c.text('Hello! Hono!'))
app.get('/error', () => {
  throw new Error('Error from Deno!!!')
})

serve(app.fetch)
```

To summarize, if you can see that the script (not in the test) works in your environment, you can merge this PR.

**Comment by sam-lippert** [comment]
I can confirm that this middleware does send errors to a live environment using Deno.

**Comment by yusukebe** [comment]
@sam-lippert 
Hi! I want to tell you about how to upload it to the npm registry. But, I'm a liitle busy. Please wait.

**Pull request merged**
